// Decompiled with JetBrains decompiler
// Type: Microsoft.Xrm.Sdk.ExecuteMultipleSettings
// Assembly: Microsoft.Xrm.Sdk, Version=9.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
// MVID: CB9267C5-A024-49B5-925F-75FBF25C45C6
// Assembly location: C:\Users\hello\.nuget\packages\microsoft.crmsdk.coreassemblies\9.0.2.46\lib\net462\Microsoft.Xrm.Sdk.dll
// XML documentation location: C:\Users\hello\.nuget\packages\microsoft.crmsdk.coreassemblies\9.0.2.46\lib\net462\Microsoft.Xrm.Sdk.xml

using System.Runtime.Serialization;

namespace Microsoft.Xrm.Sdk
{
  /// <summary>
  /// Provides support for passing in settings that control how an ExecuteMultiple message is processed.
  /// 
  /// </summary>
  [DataContract(Name = "ExecuteMultipleSettings", Namespace = "http://schemas.microsoft.com/xrm/2012/Contracts")]
  public sealed class ExecuteMultipleSettings : IExtensibleDataObject
  {
    private ExtensionDataObject _extensionDataObject;

    /// <summary>
    /// When true, then if an individual Organization Request generates an exception, the processor will add the exception to the response and continue processing.  Otherwise, any exception from the
    /// Organization Request will stop processing further requests.
    /// </summary>
    [DataMember]
    public bool ContinueOnError { get; set; }

    /// <summary>
    /// When true, the response generated by an individual Organization Request will be returned, otherwise the response will be discarded.
    /// </summary>
    [DataMember]
    public bool ReturnResponses { get; set; }

    public ExtensionDataObject ExtensionData
    {
      get => _extensionDataObject;
      set => _extensionDataObject = value;
    }
  }
}
